package edu.illinois.NIOInspector.plugin.util.extractors;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.maven.plugin.MojoExecutionException;

/**
 * Support finding the most recent log generated by the rerun Mojo.
 */
public class MostRecentLogFinder {

    private static final Logger logger = LoggerFactory.getLogger(MostRecentLogFinder.class);
    
    private static final String LOG_DIRECTORY = ".NIOInspector";

    /**
     * Find the most recent log file generated by the rerun Mojo
     * @return The most recent log file found
     * @throws MojoExecutionException if failed to find a log file in the most recent directory
     */
    public static File findMostRecentLog() throws MojoExecutionException{
        File logDirectory = new File(LOG_DIRECTORY);
        File logFile = null;

        // List all time-base named subdirectories in the .NIOInspector directory
        File[] subdirectories = logDirectory.listFiles(File::isDirectory);

        if (subdirectories != null) {
            // Sort subdirectories by timestamp (descending order)
            Arrays.sort(subdirectories, Comparator.comparingLong(MostRecentLogFinder::getTimestampFromDirectory).reversed());

            // Pick the most recent directory containing a non-empty rerun-results.log.
            // Logback contexts spawned by the project under test (e.g. per-deployment
            // classloaders) can create spurious newer timestamp directories holding an
            // empty log - those must be skipped, not treated as the latest run.
            for (File directory : subdirectories) {
                File[] files = directory.listFiles();
                if (files == null) {
                    continue;
                }
                Optional<File> rerunResultsLogFileOptional = Arrays.stream(files)
                        .filter(file -> file.getName().equals("rerun-results.log") && file.length() > 0)
                        .findFirst();
                if (rerunResultsLogFileOptional.isPresent()) {
                    logFile = rerunResultsLogFileOptional.get();
                    break;
                }
            }
            if (logFile == null) {
                throw new MojoExecutionException("Failed to find a recent rerun-results.log file");
            }
        }

        return logFile;
    }

    /**
     * Get time stamp from the time-based directory name
     * @param directory The directory with time-based name
     * @return A comparable time stamp
     */
    public static long getTimestampFromDirectory(File directory) {
        try {
            String timeBasedFileName = directory.getName();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");
            Date creationTime = dateFormat.parse(timeBasedFileName);
            return creationTime.getTime();
        } catch (Exception e) {
            logger.error("Error parsing timestamp for directory: " + directory.getPath(), e);
            return 0;
        }
    }
}
